spring:
  datasource:
    url: jdbc:postgresql://projectdb.cpn6qeamn6fy.eu-central-1.rds.amazonaws.com:5432/Customer
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
